version: '3'
services:
  badge-api:
    env_file: .env
    container_name: badge-api
    restart: always
    build: .
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
