version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/app
  badge-api:
    env_file: .env
    container_name: badge-api
    restart: always
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    links:
      - mongo
volumes:
  mongodb_data_container:
